# Generated by Django 2.2 on 2019-04-23 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CT_Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(max_length=40)),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('course_name', models.CharField(max_length=40)),
                ('CT_1', models.IntegerField(default=' ', max_length=40)),
                ('CT_2', models.IntegerField(default=' ', max_length=40)),
                ('CT_3', models.IntegerField(default=' ', max_length=40)),
                ('CT_4', models.IntegerField(default=' ', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Personal_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=40)),
                ('department', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('blood_group', models.CharField(max_length=200)),
                ('institute', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('teacher_id', models.CharField(default=' ', max_length=40)),
                ('student_id', models.CharField(default=' ', max_length=40)),
                ('department', models.CharField(default=' ', max_length=200)),
                ('hometown', models.CharField(default=' ', max_length=200)),
                ('address', models.CharField(default=' ', max_length=200)),
                ('dob', models.CharField(default=' ', max_length=200)),
                ('blood_group', models.CharField(default=' ', max_length=200)),
                ('institute', models.CharField(default=' ', max_length=400)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
